DROP TABLE IF EXISTS postagem;
DROP TABLE IF EXISTS usuario;

CREATE TABLE IF NOT EXISTS usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid UUID,
    nome VARCHAR(255),
    email VARCHAR(255),
    dob date,
    CONSTRAINT pk_usuario PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS postagem (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid UUID,
    titulo VARCHAR(255),
    corpo VARCHAR(255),
    data_criacao TIMESTAMP WITHOUT TIME ZONE,
    usuario_id BIGINT,
    CONSTRAINT pk_postagem PRIMARY KEY (id)
    );

ALTER TABLE postagem
    DROP CONSTRAINT IF EXISTS fk_postagem_on_usuario;

ALTER TABLE postagem
    ADD CONSTRAINT FK_POSTAGEM_ON_USUARIO FOREIGN KEY (usuario_id) REFERENCES usuario (id);